blank_issues_enabled: false
contact_links:
  - name: Discord Server
    url: https://discord.gg/nFFR4R4mTX
    about: Nuestro soporte Discord, si no está seguro o tiene una pregunta, no dude en buscar ayuda.
